### ISSUE TITLE
KSP 1.0.2 compatibility changes checklist

### ISSUE THREAD

**Issue by allista** [allista/hangar#166]
- [x] Air Brake -> stock
- [x] Engine Pressure Curve -> stock
- [x] Engines and Generators: heat production
- [x] Engines and Generators: heat conductivity, dissipation and thermalMass
- [ ] ModuleSurfaceFX for Engines
- [ ] bulkheadProfiles for all parts
- [ ] Dynamic DRAG CUBE generation for hangars? Oh, shit...
- [ ] Add stock ModuleCargoBay to hangars?

**Comment by Starwaster** [comment]
Drag cubes represent the part's drag from 6 different facings. They are automatically generated but for some parts may have to be manually generated. (animated parts that don't use the stock generic animator fall into this category. Ladders being an example)

**Comment by Starwaster** [comment]
ModuleCargoBay requires another module implementing the iScalarModule to properly notify the cargo bay when it is open or closed. The stock classes ModuleAnimateGeneric and ModuleProceduralFairing are the only stock classes that I know of.

If you need to see an example of how to handle it, you may refer to my mod AnimatedDecouplers: https://github.com/Starwaster/AnimatedDecouplers/blob/master/ModuleAnimatedDecoupler.cs

(The iScalarModule stuff is at the bottom. The important bits are GetScalar() tells the cargo bay what the open/closed state is) and onMoving/onStop events which need to be fired if the bay doors are moving or have stopped moving. OnStop is arguably the more important of the two as it notifies the cargo bay that it should then check for open/closed state)

**Comment by allista** [comment]
Thanks a lot!!!

**Comment by allista** [comment]
Obsolete.
